name: Release Please

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - dev

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release-please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: 'rust'
          package-name: 'copilot-cli'

      - name: Create GitHub Release
        if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release-please.outputs.tag }}
          release_name: ${{ steps.release-please.outputs.release_name }}
          body: ${{ steps.release-please.outputs.body }}