name: Release

on:
  push:
    tags: [ "*" ]

jobs:
  build_and_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: copilot-cli
            alias: linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: copilot-cli.exe
            alias: windows
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: copilot-cli
            alias: macos

    steps:
      - uses: actions/checkout@v3

      - name: Extract tag name
        shell: bash
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build Release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Run tests
        run: cargo test --verbose --target ${{ matrix.target }}

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          mv ./target/${{ matrix.target }}/release/${{ matrix.asset_name }} ./target/${{ matrix.target }}/release/${{ matrix.alias }}-${{ matrix.asset_name }}
          gh release upload ${{ env.TAG_NAME }} ./target/${{ matrix.target }}/release/${{ matrix.alias }}-${{ matrix.asset_name }} --clobber