name: Auto create pr

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  please_release:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Release Please
      uses: google-github-actions/release-please-action@v4
      id: release-please
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        release-type: 'rust'