name: Auto create pr from dev

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - dev

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release-please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: 'rust'
