name: Rust Release

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: copilot-cli
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: copilot-cli.exe

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Build Release
      run: cargo build --release --target ${{ matrix.target }}

    - name: Run tests
      run: cargo test --verbose --target ${{ matrix.target }}

    - name: Set up Release Please
      uses: google-github-actions/release-please-action@v4
      id: release-please
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        release-type: 'rust'

    - name: Upload Release Asset
      if: ${{ steps.release-please.outputs.release_created }}
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run:
        gh release upload ${{ matrix.asset_name }}-${{ matrix.os }}-${{ steps.release-please.outputs.tag_name }} ./target/${{ matrix.target }}/release/${{ matrix.asset_name }} --clobber
